Karıştırılmaması için Not:
- List, elemanları sıralanabilir, güncellenebilir ayrıca her bir eleman liste içerisinde birden fazla tekrarlanabilir. Her biri farklı veri tipinde olabilir.

- Tuple, elemanları sıralanabilir ancak güncellenemez ve her bir eleman liste içerisinde birden fazla tekrarlanabilir.

- Set, elemanları sıralanamaz ve indekslenemez ayrıca her bir eleman liste içerisinde sadece bir tane olabilir. Her biri farklı veri tipinde olabilir.

- Dictionary, key ve value şeklinde değer alırlar. Aynı key bilgisiyle birden fazla eleman olamaz.


NumPy(Bilimsel Hesaplama Kütüphanesi):
- Open-source bir kütüphanedir. İstediğimiz gibi geliştirme yapabiliriz.
- NumPy(Numerical Python): Python'da oluşturulan NumPy dizileri ile bu diziler üzerinden matematiksel işlemler yapmaya yarar.

Listeden Farkı Nedir?
- Listelerden daha hızlı çalışır.
- NumPy dizileri oluşturulurken sabit bir boyuta sahiptir.

Oluşturduğumuz listenin 1. indisindeki değeri listelerde alabiliyoruz. Buraya kadar problem yok ama "Sevgi" nin kaçıncı indiste yer aldığını bilmiyoruz. NumPy dizilerinde ise bunu gerçekleştirebiliriz.

In [6]:
names_list = ["Hayal", "Sevgi", "Nazim", "Ali"]
print(names_list[1]) 

Sevgi


In [4]:
import numpy as np

MODÜLLER:
- numpy.array: bir dizi oluşturmaya yarar.
- numpy.asarray: Numpy'da oluşturulan bir dizi nesnesini ifade eder.(Liste->Numpy array)
- numpy.ndarray: bir dizi oluşturmaya yarar.

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
#burada np.array yerine ndarray yazsaydık yine aynı sonuç olacaktı
my_array=np.array(["apple", "banana", "cherry"])
print(type(my_array))


<class 'numpy.ndarray'>


In [9]:
convert_array=np.asarray(names_list)
print(type(convert_array))

<class 'numpy.ndarray'>


- numpy.reshape: dizi verilerini değiştirmeden diziye yeni bir şekil verir. [1,3] [2,2]
- numpy.zeros: verilen şekil ve türde sıfırlarla dolu yeni bir dizi döndürür.
- numpy.concatenat: verilen eksen boyunca birdene fazla diziyi birleştirmeye yarar.

In [11]:
zeros_array = np.zeros([3, 2])
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#3,2 -> [2, 3] transpose işlemi için:
transpose=zeros_array.T
transpose

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr=np.array([1, 2, 3, 4, 5, 6,  7, 8, 9, 10, 11, 12])
print(arr)
print(len(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12


In [14]:
reshape=np.reshape(arr, (4, 3))
reshape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
array_first=np.array([[2, 4],[6, 8]])
array_second=np.array([[10, 12]])
concat=np.concatenate((array_first, array_second), axis=0)
print(concat)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [27]:
#np.arange: belirtilen aralık kadar ekrana değer yazar. For gibi.
my_range=np.arange(1, 16.0)
print(my_range)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


- numpy.split: bir diziyi görünümsel olarak birden çok alt diziye böler.
- numpy.array_split: bir diziyi birden çok alt diziye ayırmaya yarar.
- numpy.resize: bir dizinin yeniden boyutlandırılmasını sağlar.

In [28]:
my_split=np.split(my_range, 3)
my_split

[array([1., 2., 3., 4., 5.]),
 array([ 6.,  7.,  8.,  9., 10.]),
 array([11., 12., 13., 14., 15.])]

In [29]:
my_array_split= np.array_split(my_range, 5)
my_array_split

[array([1., 2., 3.]),
 array([4., 5., 6.]),
 array([7., 8., 9.]),
 array([10., 11., 12.]),
 array([13., 14., 15.])]

In [30]:
reshape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- numpy.append: bir dizinin sonuna değerler eklemeye yarar.
- numpy.insert. bir diziye  verilen eksen boyunca değerler eklemeye yarar.
- numpy.delete: Numpy'da oluşturulan bir dizi nesnesinin silinmesini sağlar.

In [31]:
np.resize(reshape, (2, 5)) #2 satır 5 sütun olacak şekilde ayarladı

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.delete(reshape, 0,0) # burada bulunan 1, 2, 3 tüm satır silindi

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.delete(reshape, 0, 1) #tüm sutun silindi

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [34]:
my_array

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [35]:
np.append(my_array, "orange") #orange eklendi

array(['apple', 'banana', 'cherry', 'orange'], dtype='<U6')

In [36]:
np.append(my_array, 11)

array(['apple', 'banana', 'cherry', '11'], dtype='<U11')

In [45]:
#numpy.insert(array, indis, values, axis = None)
np.insert(my_array, 1 , "cucumber" ) # 1. indise 2 eklendi axis yazılmasada olur. 

array(['apple', 'cucumb', 'banana', 'cherry'], dtype='<U6')

NUMPY DERS

In [47]:
number=15
print(type(number))
dir(number)

<class 'int'>


['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [ ]:
#pip install numpy
#pip3 install numpy

In [50]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([0, .5, 1, 1.5, 2])

In [51]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [52]:
array_a[3]

4

In [53]:
array_b[-1]

2.0

In [58]:
array_a[:2] #0. indisten 1. indise kadar 2 dahil değil

array([1, 2])

In [59]:
array_a.dtype

dtype('int32')

In [60]:
array_b.dtype

dtype('float64')

In [61]:
#boş array oluşturma
empty_array = np.array([])

In [62]:
empty_array.dtype #boş olan array de floattır

dtype('float64')

In [64]:
#int numpy dizisini float a çevirme
np.array([6, 8, 10], dtype=np.float_)

array([ 6.,  8., 10.])