Karıştırılmaması için Not:
- List, elemanları sıralanabilir, güncellenebilir ayrıca her bir eleman liste içerisinde birden fazla tekrarlanabilir. Her biri farklı veri tipinde olabilir.

- Tuple, elemanları sıralanabilir ancak güncellenemez ve her bir eleman liste içerisinde birden fazla tekrarlanabilir.

- Set, elemanları sıralanamaz ve indekslenemez ayrıca her bir eleman liste içerisinde sadece bir tane olabilir. Her biri farklı veri tipinde olabilir.

- Dictionary, key ve value şeklinde değer alırlar. Aynı key bilgisiyle birden fazla eleman olamaz.


NumPy(Bilimsel Hesaplama Kütüphanesi):
- Open-source bir kütüphanedir. İstediğimiz gibi geliştirme yapabiliriz.
- NumPy(Numerical Python): Python'da oluşturulan NumPy dizileri ile bu diziler üzerinden matematiksel işlemler yapmaya yarar.

Listeden Farkı Nedir?
- Listelerden daha hızlı çalışır.
- NumPy dizileri oluşturulurken sabit bir boyuta sahiptir.

Oluşturduğumuz listenin 1. indisindeki değeri listelerde alabiliyoruz. Buraya kadar problem yok ama "Sevgi" nin kaçıncı indiste yer aldığını bilmiyoruz. NumPy dizilerinde ise bunu gerçekleştirebiliriz.

In [6]:
names_list = ["Hayal", "Sevgi", "Nazim", "Ali"]
print(names_list[1]) 

Sevgi


In [5]:
import numpy as np

MODÜLLER:
- numpy.array: bir dizi oluşturmaya yarar.
- numpy.asarray: Numpy'da oluşturulan bir dizi nesnesini ifade eder.(Liste->Numpy array)
- numpy.ndarray: bir dizi oluşturmaya yarar.

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
#burada np.array yerine ndarray yazsaydık yine aynı sonuç olacaktı
my_array=np.array(["apple", "banana", "cherry"])
print(type(my_array))


<class 'numpy.ndarray'>


In [9]:
convert_array=np.asarray(names_list)
print(type(convert_array))

<class 'numpy.ndarray'>


- numpy.reshape: dizi verilerini değiştirmeden diziye yeni bir şekil verir. [1,3] [2,2]
- numpy.zeros: verilen şekil ve türde sıfırlarla dolu yeni bir dizi döndürür.
- numpy.concatenat: verilen eksen boyunca birdene fazla diziyi birleştirmeye yarar.

In [11]:
zeros_array = np.zeros([3, 2])
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#3,2 -> [2, 3] transpose işlemi için:
transpose=zeros_array.T
transpose

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr=np.array([1, 2, 3, 4, 5, 6,  7, 8, 9, 10, 11, 12])
print(arr)
print(len(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
12


In [14]:
reshape=np.reshape(arr, (4, 3))
reshape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
array_first=np.array([[2, 4],[6, 8]])
array_second=np.array([[10, 12]])
concat=np.concatenate((array_first, array_second), axis=0)
print(concat)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [27]:
#np.arange: belirtilen aralık kadar ekrana değer yazar. For gibi.
my_range=np.arange(1, 16.0)
print(my_range)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


- numpy.split: bir diziyi görünümsel olarak birden çok alt diziye böler.
- numpy.array_split: bir diziyi birden çok alt diziye ayırmaya yarar.
- numpy.resize: bir dizinin yeniden boyutlandırılmasını sağlar.

In [28]:
my_split=np.split(my_range, 3)
my_split

[array([1., 2., 3., 4., 5.]),
 array([ 6.,  7.,  8.,  9., 10.]),
 array([11., 12., 13., 14., 15.])]

In [29]:
my_array_split= np.array_split(my_range, 5)
my_array_split

[array([1., 2., 3.]),
 array([4., 5., 6.]),
 array([7., 8., 9.]),
 array([10., 11., 12.]),
 array([13., 14., 15.])]

In [30]:
reshape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- numpy.append: bir dizinin sonuna değerler eklemeye yarar.
- numpy.insert. bir diziye  verilen eksen boyunca değerler eklemeye yarar.
- numpy.delete: Numpy'da oluşturulan bir dizi nesnesinin silinmesini sağlar.

In [31]:
np.resize(reshape, (2, 5)) #2 satır 5 sütun olacak şekilde ayarladı

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.delete(reshape, 0,0) # burada bulunan 1, 2, 3 tüm satır silindi

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.delete(reshape, 0, 1) #tüm sutun silindi

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [34]:
my_array

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [35]:
np.append(my_array, "orange") #orange eklendi

array(['apple', 'banana', 'cherry', 'orange'], dtype='<U6')

In [36]:
np.append(my_array, 11)

array(['apple', 'banana', 'cherry', '11'], dtype='<U11')

In [45]:
#numpy.insert(array, indis, values, axis = None)
np.insert(my_array, 1 , "cucumber" ) # 1. indise 2 eklendi axis yazılmasada olur. 

array(['apple', 'cucumb', 'banana', 'cherry'], dtype='<U6')

NUMPY DERS

In [47]:
number=15
print(type(number))
dir(number)

<class 'int'>


['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 '

In [ ]:
#pip install numpy
#pip3 install numpy

In [11]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([0, .5, 1, 1.5, 2])

In [51]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [52]:
array_a[3]

4

In [53]:
array_b[-1]

2.0

In [58]:
array_a[:2] #0. indisten 1. indise kadar 2 dahil değil

array([1, 2])

In [59]:
array_a.dtype

dtype('int32')

In [60]:
array_b.dtype

dtype('float64')

In [61]:
#boş array oluşturma
empty_array = np.array([])

In [62]:
empty_array.dtype #boş olan array de floattır

dtype('float64')

In [64]:
#int numpy dizisini float a çevirme
np.array([6, 8, 10], dtype=np.float_)

array([ 6.,  8., 10.])

In [3]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [6]:
string_array=np.array(["tuba", "akbas"])

In [8]:
string_array.dtype

dtype('<U5')

Dimensions and Shapes

Shape: Numpy array nesnesinin kaç satır ve sütundan oluştuğunu gösteren bir tupple nesnesi döndürür

In [10]:
my_array=np.array([
    [1, 2, 3],
    [4, 5, 6]
    
])

In [17]:
array_a.shape #

(4,)

In [16]:
array_b.shape

(5,)

In [18]:
my_array.shape #2 satır 3 sütun

(2, 3)

In [19]:
my_array.ndim #2 eleman

2

In [20]:
my_array.size 
#her bir köşeli parantezdi bulunan elemanların sayısı

6

In [24]:
my_array= np.array([
  [
      [12, 11, 10],
      [9, 8, 7]
      
  ]  ,
  [
       [6, 5, 4],
       [3, 2, 1]  
  ]
    
])

In [22]:
my_array.ndim

3

In [25]:
my_array.shape 

(2, 2, 3)

In [26]:
my_array.size

12

In [27]:
my_array=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    
])

In [28]:
my_array[1]

array([4, 5, 6])

In [29]:
my_array[1][0]

4

In [30]:
my_array[1, 0]

4

In [31]:
my_array[0:2] #0. satırdan 1. satıra kadar al

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array[:1, :3] #1. satır 3 sutun

array([[1, 2, 3]])

In [38]:
my_array[:2, : 2] #2. satıra kadar 2 sutun

array([[1, 2],
       [4, 5]])

In [39]:
my_array[::] #tümünü alır

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
my_array[1]=np.array([10, 10, 10]) #1. satır değiştirlidi
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [42]:
my_array[2]=99 #tek olarak yazılmasına rağmen 3 kere yazıldı
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [43]:
np.arange(1, 10, 2) #1'den 10 a kadar (10 dahil değil), 2'şer artarak

array([1, 3, 5, 7, 9])

In [50]:
my_array_=np.arange(0, 10)
my_array_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
my_array_.reshape(5, 2) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [54]:
np.zeros(2)

array([0., 0.])

In [55]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
np.ones((2, 5, 3)) #2 elemanlı 5 satırlı 3 sutunlu

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [61]:
#Belirlenen boyutlardabirim matris oluşturmamızı sağlar.
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
my_array=np.random.random((5, 2))
my_array

array([[0.52251803, 0.75259668],
       [0.68825032, 0.16128832],
       [0.59006174, 0.30541203],
       [0.43449832, 0.71436536],
       [0.95935316, 0.01101147]])

In [63]:
np.random.randint(100, size=(3,3))

array([[ 9, 81, 50],
       [18,  2, 48],
       [63, 74, 37]])

In [64]:
np.linspace(5, 10, 3) #5'ten 10'a kadar 3 sütunluk

array([ 5. ,  7.5, 10. ])

# any(), all(), full(), concatenate()

full() metodu başlıca 2 parametre alır. İlki istenilen dizinin boyutu, ikincisi ise dizinin hangi sayıdan oluşacağı.(2,3)’lük bir matrisin sadece 8 değerini içermesini isteyelim

In [66]:
np.full((2, 3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [67]:
array1=np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
array1=array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.concatenate([array1, array1]) #? axis=0

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
np.concatenate([array1, array1], axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

Statistics

In [83]:
array1.sum()

45

In [84]:
array1.mean()

4.5

In [85]:
array1.std()

2.8722813232690143

In [86]:
array1.var()

8.25

In [87]:
array1.sum(axis=1)

array([10, 35])

In [89]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [90]:
array1+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
array1+=10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
array_example=np.arange(0, 10)
array_example=array_example.reshape(5,2)
array_example

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
array_example + 10
array_example

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
array_example+=10
array_example

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

Boolean Arrays:

In [96]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [97]:
a[0], a[-1]

(0, 3)

In [98]:
a[[0, -1]]

array([0, 3])

In [102]:
a [[True, True, False, True]] #?

array([0, 1, 3])

In [103]:
a[[True, False, False, True]] #???

array([0, 3])

In [105]:
bool_idx=(a>2) #a dizisinde 2 den büyük elemanlar
bool_idx

array([False, False, False,  True])

In [106]:
a.mean()

1.5

In [109]:
a

array([0, 1, 2, 3])

In [110]:
a>a.mean()

array([False, False,  True,  True])

In [111]:
a[a>a.mean()] #2. ve 3. değerler mi demek istiyor?

array([2, 3])

In [112]:
a[~(a>a.mean())] #0. ve 1. değerler koşulu sağlamyıor

array([0, 1])

In [113]:
a[(a==0)| (a==1)]

array([0, 1])

In [114]:
a[(a<=2) & (a%2==0)] # ?

array([0, 2])

* 100'e kadar rastgale tamsayılardan oluşan (3, 3) bir matris oluşturun.
* 30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [116]:
rand_array=np.random.randint(100, size=(3, 3))
rand_array

array([[84, 12, 97],
       [89, 78, 76],
       [20, 69, 17]])

In [117]:
boolean_array=rand_array>30
boolean_array

array([[ True, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [118]:
rand_array[boolean_array] #sadece true olanları yazdırdı

array([84, 97, 89, 78, 76, 69])

np.dot(): metodu sonuç olarak aldığı iki Numpy dizininin nokta çarpımı ya da bir diğer adıyla skaler çarpımını döndürür.

In [119]:
a = np.array([[1,2],[3,4]])
b = np.array(([5,6],[7,8]))
print('Birinci Çıktı:', np.dot(a,b))
print('İkinci Çıktı:', a@b)
print('Üçüncü Çıktı:', np.matmul(a,b))

Birinci Çıktı: [[19 22]
 [43 50]]
İkinci Çıktı: [[19 22]
 [43 50]]
Üçüncü Çıktı: [[19 22]
 [43 50]]


In [120]:
my_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [122]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [123]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [1]:
import sys

In [3]:
sys.getsizeof(4) #nesnenin depolama boyutunu bulur ve bayt cinsinden döndürür.

28

In [4]:
sys.getsizeof(1000**100)

160

In [14]:
sys.getsizeof(2000**3)

32

In [10]:
#itemsize: Dizideki elemanların byte cinsinden boyutudur. 
# Yani tek bir dizi elemanın boyutudur. 
# int32 ise itemsize değeri 32/8=4 Byte
np.dtype(int).itemsize 

4

In [15]:
np.dtype(np.int8).itemsize

1

In [16]:
#float64 ise itemsize değeri 64/8=8 Byte
np.dtype(float)

dtype('float64')

In [17]:
np.dtype(float).itemsize

8

In [18]:
sys.getsizeof([4])

64

In [19]:
sys.getsizeof([1, 4])

72

In [22]:
sys.getsizeof([5, 4, 3])

88

In [23]:
#nbytes: Dizinin harcadığı toplam byte sayısıd
np.array([1, 2, 3]).nbytes

12

In [24]:
my_list=list(range(100000))
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [25]:
my_array=np.arange(100000)
my_array

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [29]:
import time

In [30]:
%time np.sum(my_array**2)

CPU times: total: 0 ns
Wall time: 0 ns


216474736

In [31]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 0 ns
Wall time: 16.4 ms


333328333350000